version: "3.7"

services:

  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    restart: always

  web-service:
    container_name: piranha-web-razor-behind-ngnix
    depends_on:
      - reverseproxy
    build:
      context: ./piranha-razor
      dockerfile: Dockerfile
      args:
        - project_name=RazorWeb
        - project_path=piranha.core/examples/RazorWeb/
        - git_repo=https://github.com/PiranhaCMS/piranha.core.git
    expose:
      - "5000"
    restart: always