version: "3.7"

services:

  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  web-service:
    image: geekcafe/piranha-razor-sqlite:latest
    container_name: piranha-web-razor-behind-nginx
    depends_on:
      - reverseproxy    
    expose:
      - "5000"
    restart: always